openapi: 3.0.0
info:
  version: 1.0.0
  title: ChangeHTTPMethodInvokeApi
  x-ibm-name: changehttpmethodinvokeapi
servers:
  - url: /changehttpmethodinvokeapi
x-ibm-configuration:
  properties:
    target-url:
      value: >-
        https://api.eu-gb.apiconnect.appdomain.cloud/prashapi123gmailcom-dev/sb/customerservice/getcustomer
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          persistent-connection: true
    catch: []
    finally: []
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
paths:
  /getCustomerDetails:
    get:
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                title: Customer
                type: object
      parameters:
        - name: Id
          in: header
          schema:
            title: Id
            type: integer
